# -*- ruby -*-
# encoding: utf-8

source 'https://rubygems.org'

gem 'grpc', '~> 1.34'
gem 'grpc-tools', '~> 1.34'
gem 'mongo', '~> 2.14'
gem 'json', '~> 2.5', '>= 2.5.1'
gem 'puma', '~> 5.1', '>= 5.1.1'
gem 'sinatra', '~> 2.1'
gem 'rack-ssl', '~> 1.4', '>= 1.4.1'
gem 'sinatra-contrib'
gemspec