# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth/v1/auth.proto for package 'auth'

require 'grpc'
require 'auth/v1/auth_pb'

module Auth
  module Auth
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'auth.Auth'

      # Sends a greeting
      rpc :SayHello, ::Auth::HelloRequest, ::Auth::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
