version: '3'

services:
  web-app:
    container_name: web-app
    restart: always
    build: ./app
    ports:
      - '80:80'
    links:
      - api-service
    volumes:
      - ./app:/app
      
  api-service:
    container_name: todo-api
    restart: always
    build: ./services/api
    ports:
      - '1000:1000'
    links:
      - task-service
      - auth-service
    volumes:
      - ./services/api:/api-service
      
  auth-service:
    container_name: auth-service
    restart: always
    build: ./services/auth
    ports: 
      - '8080:8080'
      - '8081:8081'
    depends_on:
          - "authdb"
    volumes:
      - ./services/auth/src:/auth-service/src
      - ./services/auth/lib:/auth-service/lib
      - ./services/auth/protos:/auth-service/protos

  task-service:
    container_name: task-service
    restart: always
    build: ./services/task
    ports: 
      - '50051:50051'
      - '50052:50052'
    links:
      - taskdb
    depends_on:
          - "taskdb"
    volumes:
      - ./services/task/src:/task-service/src
      - ./services/task/lib:/task-service/lib
      - ./services/task/protos:/task-service/protos


  taskdb:
    image: mongo
    container_name: taskdb # connect using url=mongodb://taskdb:27017
    ports: 
      - '27017:27017'
    volumes:
      - task-mongodb-volume:/data/db

  authdb:
    image: mongo
    container_name: authdb # connect using url=mongodb://taskdb:27017
    ports: 
      - '27018:27018'
    volumes:
      - auth-mongodb-volume:/data/db 

volumes:
  task-mongodb-volume:  
  auth-mongodb-volume:  