version: '3'

services:

  # REST-API-Service
  api-service:
    container_name: api-service
    restart: always
    build: ./services/api
    ports: 
      - '8080:8080'
    links: 
      - task-service
    depends_on:
          - "task-service"
    volumes:
      - ./services/api:/api-service

  # Task-Service
  task-service:
    container_name: task-service
    restart: always
    build: ./services/task
    ports: 
      - '50051:50051'
    links:
      - taskdb
    depends_on:
          - "taskdb"
    volumes:
      - ./services/task:/task-service


  # Task-Service database
  taskdb:
    image: mongo
    container_name: taskdb # connect using url=mongodb://taskdb:27017
    ports: 
      - '27017:27017'
    volumes:
      - task-mongodb-volume:/data/db
volumes:
  task-mongodb-volume:  