version: '3'

services:
  # web-app:
  #   container_name: web-app
  #   restart: always
  #   build: ./app
  #   ports:
  #     - '80:80'
  #   links:
  #     - api-service
  #   volumes:
  #     - ./app:/app
  #   environment: 
  #     - ENVIROMENT=development

  api-service:
    container_name: todo-api
    restart: always
    build: ./services/api
    ports:
      - '1000:1000'
    links:
      - task-service
      - auth-service
    volumes:
      - ./services/api/etc/nginx/conf.d/:/etc/nginx/conf.d/
    environment: 
      - ENVIROMENT=development

  auth-service:
    container_name: auth-service
    restart: always
    build: ./services/auth
    ports: 
      - '8080:8080'
      - '8081:8081'
    depends_on:
          - "authdb"
    volumes:
      - ./services/auth:/auth-service
    environment: 
      - ENVIROMENT=development
    
  user-service:
    container_name: user-service
    restart: always
    build: ./services/user
    ports: 
      - '30051:30051'
      - '30052:30052'
    links:
      - taskdb
    depends_on:
          - "userdb"
    volumes:
      - ./services/user:/user-service
    environment: 
      - GIN_MODE=debug

  task-service:
    container_name: task-service
    restart: always
    build: ./services/task
    ports: 
      - '50051:50051'
      - '50052:50052'
    links:
      - taskdb
    depends_on:
          - "taskdb"
    volumes:
      - ./services/task:/task-service
    environment: 
      - ENVIROMENT=development


  taskdb:
    image: mongo
    container_name: taskdb # connect using url=mongodb://taskdb:27017
    ports: 
      - '27017:27017'
    volumes:
      - task-mongodb-volume:/data/db

  authdb:
    image: mongo
    container_name: authdb # connect using url=mongodb://authdb:27017
    ports: 
      - '27018:27017'
    volumes:
      - auth-mongodb-volume:/data/db 

  userdb:
    image: mongo
    container_name: userdb # connect using url=mongodb://userdb:27017
    ports: 
      - '27019:27017'
    volumes:
      - user-mongodb-volume:/data/db 






volumes:
  task-mongodb-volume:  
  auth-mongodb-volume:  