version: '3'

services:
  api-service:
    container_name: todo-api
    restart: always
    build: ./services/api
    ports:
      - 1000:1000
    links:
      - task-service
      - auth-service
    volumes:
      - ./services/api/etc/nginx/conf.d/:/etc/nginx/conf.d/
    environment: 
      - ENVIROMENT=development

  auth-service:
    container_name: auth-service
    restart: always
    build: ./services/auth
    ports: 
      - 10051:10051
      - 10052:10052
    depends_on:
          - "authdb"
    volumes:
      - ./services/auth/service:/auth-service/service
    environment: 
      - ENVIROMENT=development
    
  user-service:
    container_name: user-service
    restart: always
    build: ./services/user
    ports: 
      - 30051:30051
      - 30052:30052
    links:
      - userdb
    depends_on:
          - "userdb"
    volumes:
      - ./services/user:/user-service
    environment: 
      - GIN_MODE=debug

  task-service:
    container_name: task-service
    restart: always
    build: ./services/task
    ports: 
      - 50051:50051
      - 50052:50052
    links:
      - taskdb
    depends_on:
          - "taskdb"
    volumes:
      - ./services/task:/task-service
    environment: 
      - ENVIROMENT=development

  taskdb:
    image: mongo
    container_name: taskdb # connect using url=mongodb://taskdb:27017
    ports: 
      - '27017:27017'
    volumes:
      - task-mongodb-volume:/data/db

  authdb:
    image: mongo
    container_name: authdb # connect using url=mongodb://authdb:27017
    ports: 
      - '27018:27017'
    volumes:
      - auth-mongodb-volume:/data/db 

  userdb:
    image: mongo
    container_name: userdb # connect using url=mongodb://userdb:27019
    ports: 
      - '27019:27017'
    volumes:
      - user-mongodb-volume:/data/db 



volumes:
  task-mongodb-volume:  
  user-mongodb-volume:  
  auth-mongodb-volume:  