# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/v1/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user/v1/user.proto", :syntax => :proto3) do
    add_message "user.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "user.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module User
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("user.HelloReply").msgclass
end
