# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user/v1/user.proto for package 'user'

require 'grpc'
require 'user/v1/user_pb'

module User
  module User
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'user.User'

      # Sends a greeting
      rpc :SayHello, ::User::HelloRequest, ::User::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
