# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task/v1/task.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("task/v1/task.proto", :syntax => :proto3) do
    add_message "task.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "task.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Task
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("task.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("task.HelloReply").msgclass
end
