# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: task/v1/task.proto for package 'task'

require 'grpc'
require 'task/v1/task_pb'

module Task
  module Task
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'task.Task'

      # Sends a greeting
      rpc :SayHello, ::Task::HelloRequest, ::Task::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
